version: 2

sources:
  - name: raw
    tables:
      - name: raw_sales

models:
  - name: stg_sales
    description: "Cleaned staging table for sales data"
    columns:
      - name: invoice_no
        tests:
          - not_null
      - name: stock_code
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: unit_price
        tests:
          - not_null

  - name: fct_daily_revenue
    description: "Fact table aggregating revenue per day"
    columns:
      - name: sale_date
        tests:
          - not_null
      - name: daily_revenue
        tests:
          - not_null
